[package]
name = "twapi"
version = "0.4.3"
authors = ["aoyagikouhei <aoyagi.kouhei@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A simple Twitter library. This is easy for customize."
repository = "https://github.com/aoyagikouhei/twapi-rs"
keywords = ["twitter", "oauth"]
categories = ["api-bindings"]
readme = "Readme.md"
documentation = "https://docs.rs/twapi"

[dependencies]
base64 = "~0.10.1"
chrono = "~0.4.6"
rand = "~0.6.5"
rust-crypto = "~0.2.36"
url = "~1.7.2"
reqwest = "~0.9.15"
serde_json = "~1.0.39"
ipnetwork = { version = "~0.14.0", optional = true }

[features]
account-activity = [ "ipnetwork" ]