[package]
name = "twapi"
version = "0.5.0"
authors = ["aoyagikouhei <aoyagi.kouhei@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A simple Twitter library. This is easy for customize."
repository = "https://github.com/aoyagikouhei/twapi-rs"
keywords = ["twitter", "oauth"]
categories = ["api-bindings"]
readme = "Readme.md"
documentation = "https://docs.rs/twapi"
edition = "2018"

[dependencies]
base64 = "~0.10.1"
url = "~1.7.2"
reqwest = "~0.9.18"
serde_json = "~1.0.39"
ipnetwork = { version = "~0.14.0", optional = true }
twapi-oauth = "~0.1.1"

[features]
account-activity = [ "ipnetwork" ]

