[package]
name = "twapi"
version = "0.4.0"
authors = ["aoyagikouhei <aoyagi.kouhei@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A simple Twitter library. This is easy for customize."
repository = "https://github.com/aoyagikouhei/twapi-rs"
keywords = ["twitter", "oauth"]
categories = ["api-bindings"]
readme = "Readme.md"
documentation = "https://docs.rs/twapi"

[dependencies]
base64 = "~0.9.0"
chrono = "~0.4.0"
rand = "~0.4.2"
rust-crypto = "~0.2.36"
url = "~1.7.0"
reqwest = "~0.8.5"
serde_json = "~1.0.10"
ipnetwork = { version = "~0.12.8", optional = true }

[features]
account-activity = [ "ipnetwork" ]