[package]
name = "account-activity-web-rs"
version = "0.1.0"
authors = ["aoyagikouhei <aoyagi.kouhei@gmail.com>"]

[dependencies]
gotham = "~0.2.0"
gotham_derive = "~0.2.0"
hyper = "0.11"
futures = "~0.1.11"
mime = "0.3"
serde = "~1.0.33"
serde_derive = "~1.0.33"
twapi = { path = "../.." }